<a href="https://colab.research.google.com/github/nourozkhan/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**
\
Numpy stands for Numerical Python. Its is a Python Libraray used for working with array. Its is the fundamental package for scientific computing.

In [ ]:
import numpy as np

# To create one dimensional array
a = np.array([1,2,3,4])
print(a)
print(a[1])
print(a.ndim)
print(a.itemsize)
print(a.dtype)


[1 2 3 4]
2
1
8
int64


In [ ]:
d = np.array([5,6,7,8])

#some statistics function
print(d.max())
print(d.min())
print(d.sum())

#arthmatic operations
print(a+d)
print(d-a)
print(a*d)
print(d/a)
print(d%a)
print(a.dot(d))

8
5
26
[ 6  8 10 12]
[4 4 4 4]
[ 5 12 21 32]
[5.         3.         2.33333333 2.        ]
[0 0 1 0]
70


In [ ]:
# To create two dimensional array
b = np.array([[1,2],[3,4],[5,6]], dtype=float)
print(b)
print(b[1])
print(b.size)
print(b.shape)
print(b.reshape(2,3))
print(b.ravel())

[[1. 2.]
 [3. 4.]
 [5. 6.]]
[3. 4.]
6
(3, 2)
[[1. 2. 3.]
 [4. 5. 6.]]
[1. 2. 3. 4. 5. 6.]


In [ ]:
c = np.arange(0,11)
print(c)

# for Odd numbers
odd_numbers = np.arange(1,10,2)
print(odd_numbers)
# for Even numbers
even_numbers = np.arange(2,11,2)
print(even_numbers)
# to generate table of three
three_table = np.arange(3,36,3)
print(three_table)
# for square root
print(np.sqrt(even_numbers))
# for square
print(even_numbers ** 2)

[ 0  1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]
[ 2  4  6  8 10]
[ 3  6  9 12 15 18 21 24 27 30 33]
[1.41421356 2.         2.44948974 2.82842712 3.16227766]
[  4  16  36  64 100]
